# Generated by Django 5.0.3 on 2024-03-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="img",
            field=models.ImageField(default=None, upload_to="user_profile/"),
        ),
    ]
