# Generated by Django 5.0.3 on 2024-03-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_comment_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.CharField(max_length=1000),
        ),
    ]
