# Generated by Django 5.0.3 on 2024-03-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
