# Generated by Django 5.0.3 on 2024-03-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_post_video_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymousPost",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="anonymous_images/")),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="anonymous_videos/"
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
