# Generated by Django 5.0.3 on 2024-03-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_anonymouspost"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymouspost",
            name="is_valid",
            field=models.BooleanField(default=False),
        ),
    ]
